[package]

name = "hkg"
version = "0.0.1"
authors = [ "u59u75u65" ]

[dependencies]
hyper = "0.8"
kuchiki = "*"
rustbox = "*"
rustc-serialize = "0.3"
chrono = "0.2"
regex = "0.1"
cancellation = "0.1"

[dependencies.url]
git = "https://github.com/servo/rust-url"
